### ISSUE TITLE
Determine why requests to core.trac.wordpress.org are hitting a rate limit

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/rave#14]
The core.trac.wordpress.org job is hitting a rate limit and causing the workflow to fail: https://github.com/johnbillion/rave-wordpress/actions/workflows/rave.yml

```
Run wget -O package.zip "https://core.trac.wordpress.org/browser/tags/6.7?format=zip"
--2024-11-17 22:03:28--  https://core.trac.wordpress.org/browser/tags/6.7?format=zip
Resolving core.trac.wordpress.org (core.trac.wordpress.org)... 198.143.164.246
Connecting to core.trac.wordpress.org (core.trac.wordpress.org)|198.143.164.246|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2024-11-17 22:03:28 ERROR 429: Too Many Requests.

Error: Process completed with exit code 8.
```

**Comment by johnbillion** [comment]
In e5ca054 I've temporarily disabled reproduction from the `core.trac.wordpress.org` ZIP while I investigate rate limiting.

**Comment by szepeviktor** [comment]
Is this the only place you download from core.trac × 3 versions?
https://github.com/johnbillion/rave-wordpress/blob/05918c73858cdf38e543423fbe585ecc60dfb087/.github/workflows/reproduce.yml#L55

**Comment by johnbillion** [comment]
Yep, and three times in quick succession due to the three jobs running in parallel

**Comment by szepeviktor** [comment]
I get HTTP/429 right away on the first request, even with
```
--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
--referer="https://core.trac.wordpress.org/browser/tags/6.7"
```

**Comment by szepeviktor** [comment]
I think core.trac does not allow datacenters.

**Comment by szepeviktor** [comment]
`HTTP/1.1 200 Ok` from my consumer ISP line. Many times!

**Comment by szepeviktor** [comment]
@johnbillion This is a horrible service but may be to your help here.
https://github.com/boywithkeyboard-archive/warp
`- uses: boywithkeyboard/warp@v1`
